// AUTO-GENERATED FILE - DO NOT EDIT
export const filters = {
  Atenas: {
    neighbourhoods: [
      '1Ο ΝΕΚΡΟΤΑΦΕΙΟ',
      'ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ',
      'ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ',
      'ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ',
      'ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ',
      'ΑΚΡΟΠΟΛΗ',
      'ΑΜΠΕΛΟΚΗΠΟΙ',
      'ΑΝΩ ΚΥΨΕΛΗ',
      'ΑΝΩ ΠΑΤΗΣΙΑ',
      'ΒΟΤΑΝΙΚΟΣ',
      'ΓΚΑΖΙ',
      'ΓΚΥΖΗ',
      'ΓΟΥΒΑ',
      'ΓΟΥΔΙ',
      'ΕΛΛΗΝΟΡΩΣΩΝ',
      'ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ',
      'ΖΑΠΠΕΙΟ',
      'ΘΗΣΕΙΟ',
      'ΙΛΙΣΙΑ',
      'ΚΕΡΑΜΕΙΚΟΣ',
      'ΚΟΛΟΚΥΝΘΟΥ',
      'ΚΟΛΩΝΑΚΙ',
      'ΚΟΛΩΝΟΣ',
      'ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ',
      'ΚΥΨΕΛΗ',
      'ΛΥΚΑΒΗΤΤΟΣ',
      'ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ',
      'ΝΕΑ ΚΥΨΕΛΗ',
      'ΝΕΟΣ ΚΟΣΜΟΣ',
      'ΝΙΡΒΑΝΑ',
      'ΠΑΓΚΡΑΤΙ',
      'ΠΑΤΗΣΙΑ',
      'ΠΕΔΙΟ ΑΡΕΩΣ',
      'ΠΕΝΤΑΓΩΝΟ',
      'ΠΕΤΡΑΛΩΝΑ',
      'ΠΛΑΤΕΙΑ ΑΜΕΡΙΚΗΣ',
      'ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ',
      'ΠΟΛΥΓΩΝΟ',
      'ΠΡΟΜΠΟΝΑ',
      'ΡΗΓΙΛΛΗΣ',
      'ΡΙΖΟΥΠΟΛΗ',
      'ΣΕΠΟΛΙΑ',
      'ΣΤΑΔΙΟ',
      'ΣΤΑΘΜΟΣ ΛΑΡΙΣΗΣ',
    ],
    years: [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Madrid: {
    neighbourhoods: [
      'Arganzuela',
      'Barajas',
      'Carabanchel',
      'Centro',
      'Chamartín',
      'Chamberí',
      'Ciudad Lineal',
      'Fuencarral - El Pardo',
      'Hortaleza',
      'Latina',
      'Moncloa - Aravaca',
      'Moratalaz',
      'Puente de Vallecas',
      'Retiro',
      'Salamanca',
      'San Blas - Canillejas',
      'Tetuán',
      'Usera',
      'Vicálvaro',
      'Villa de Vallecas',
      'Villaverde',
    ],
    years: [2012, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Lisboa: {
    neighbourhoods: [
      'Alenquer',
      'Amadora',
      'Arruda Dos Vinhos',
      'Azambuja',
      'Cadaval',
      'Cascais',
      'Lisboa',
      'Loures',
      'Lourinh',
      'Mafra',
      'Odivelas',
      'Oeiras',
      'Sintra',
      'Sobral De Monte Agrao',
      'Torres Vedras',
      'Vila Franca De Xira',
    ],
    years: [2011, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Amesterdão: {
    neighbourhoods: [
      'Bijlmer-Centrum',
      'Bijlmer-Oost',
      'Bos en Lommer',
      'Buitenveldert - Zuidas',
      'Centrum-Oost',
      'Centrum-West',
      'De Aker - Nieuw Sloten',
      'De Baarsjes - Oud-West',
      'De Pijp - Rivierenbuurt',
      'Gaasperdam - Driemond',
      'Geuzenveld - Slotermeer',
      'IJburg - Zeeburgereiland',
      'Noord-Oost',
      'Noord-West',
      'Oostelijk Havengebied - Indische Buurt',
      'Osdorp',
      'Oud-Noord',
      'Oud-Oost',
      'Slotervaart',
      'Watergraafsmeer',
      'Westerpark',
      'Zuid',
    ],
    years: [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Antwerp: {
    neighbourhoods: [
      'Amandus - Atheneum',
      'Borgerhout Extra Muros',
      'Borgerhout Intra Muros Noord',
      'Borgerhout Intra Muros Zuid',
      'Brederode',
      'Centraal Station',
      'Dam',
      'Deurne Dorp - Gallifort',
      'Deurne Noord',
      'Deurne Oost',
      'Deurne Zuid Oost',
      'Deurne Zuid West',
      'Donk',
      'Eilandje',
      'Ekeren Centrum',
      'Groenenhoek',
      'Haringrode',
      'Harmonie',
      'Historisch Centrum',
      'Hoboken - Centrum',
      'Hoboken - Noord',
      'Hoboken - West',
      'Hoboken - Zuidoost',
      'Hoogte',
      'Kiel',
      'Koornbloem',
      'Kruininge - Bremweide',
      'Lambrechtshoeken',
      'Leugenberg',
      'Linkeroever',
      'Mariaburg',
      'Markgrave',
      'Merksem - Heide',
      'Middelheim',
      'Neerland',
      'Nieuw - Kwartier Oost',
      'Nieuw - Kwartier West',
      'Nieuw - Zuid',
      'Nieuwdreef',
      'Oosterveld - Elsdonk',
      'Oud - Berchem',
      'Oud - Merksem',
      'Polder',
      'Schoonbroek-Rozemaai',
      'Sint-Andries',
      'Stadspark',
      'Stuivenberg',
      'Tentoonstellingswijk',
      'Theaterbuurt-Meir',
      'Tuinwijk',
      'Universiteitsbuurt',
      'Valaar',
      'Wilrijk Centrum',
      'Zuid',
      'Zurenborg',
    ],
    years: [2015, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Florida: {
    neighbourhoods: [
      'Coconut Creek',
      'Cooper City',
      'Coral Springs',
      'County Regional Facility',
      'Dania Beach',
      'Davie',
      'Deerfield Beach',
      'Fort Lauderdale',
      'Hallandale Beach',
      'Hillsboro Beach',
      'Hollywood',
      'Lauderdale By The Sea',
      'Lauderdale Lakes',
      'Lauderhill',
      'Lazy Lake',
      'Lighthouse Point',
      'Margate',
      'Miramar',
      'North Lauderdale',
      'Oakland Park',
      'Parkland',
      'Pembroke Park',
      'Pembroke Pines',
      'Plantation',
      'Pompano Beach',
      'Sea Ranch Lakes',
      'Southwest Ranches',
      'Sunrise',
      'Tamarac',
      'Tribal Land',
      'Unincorporated',
      'West Park',
      'Weston',
      'Wilton Manors',
    ],
    years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Boston: {
    neighbourhoods: [
      'Allston',
      'Back Bay',
      'Bay Village',
      'Beacon Hill',
      'Brighton',
      'Charlestown',
      'Chinatown',
      'Dorchester',
      'Downtown',
      'East Boston',
      'Fenway',
      'Hyde Park',
      'Jamaica Plain',
      'Leather District',
      'Longwood Medical Area',
      'Mattapan',
      'Mission Hill',
      'North End',
      'Roslindale',
      'Roxbury',
      'South Boston',
      'South Boston Waterfront',
      'South End',
      'West End',
      'West Roxbury',
    ],
    years: [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
  Cambridge: {
    neighbourhoods: [
      'Agassiz',
      'Area 2/MIT',
      'Cambridge Highlands',
      'Cambridgeport',
      'East Cambridge',
      'Mid-Cambridge',
      'Neighborhood Nine',
      'North Cambridge',
      'Riverside',
      'Strawberry Hill',
      'The Port',
      'Wellington-Harrington',
      'West Cambridge',
    ],
    years: [2013, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    property_types: ['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
  },
} as const
